# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MyResearch',
                'doc_host': 'https://apingali.github.io',
                'git_url': 'https://github.com/apingali/MyResearch',
                'lib_path': 'MyResearch'},
  'syms': {'MyResearch.core': {'MyResearch.core.foo': ('core.html#foo', 'MyResearch/core.py')}}}
